// tools/lib/generate.mjs
// Renders pitch's team+player CSV shape into the same ESM data-file format
// src/csv_to_league.py used to produce (ES module export, not the old
// window.X assignment - pitch moved to real ES modules before this phase).
// Mirrors generate_js() in csv_to_league.py field-for-field.
import { POSITION_ORDER } from './leagueSchema.mjs';
import { flagForDemonym } from './nationality.mjs';

const DETAILED_ATTRIBUTE_KEYS = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physical'];

function escapeJs(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function detailedArg(player, key) {
  const value = Number(player?.[key]);
  return Number.isFinite(value) ? String(Math.round(value)) : 'null';
}

// helperName(id, name, [nationality,] position, age, attack, midfield, defence, gk, value_£m, wage_£k/w, potential, is_wonderkid, pace, shooting, passing, dribbling, defending, physical)
export function buildLeagueJs({ teams, playersByTeam, arrayName, helperName, sourceLabel, hasNationality }) {
  const lines = [];
  const totalPlayers = teams.reduce((sum, t) => sum + (playersByTeam.get(t.team_id) || []).length, 0);
  lines.push('/**');
  lines.push(` * Auto-generated by tools/csv-to-league.mjs`);
  lines.push(` * ${teams.length} teams, ${totalPlayers} players`);
  lines.push(` * League: ${teams[0]?.league || sourceLabel}`);
  lines.push(' *');
  const sig = hasNationality
    ? ` * ${helperName}(id, name, nationality, position, age, attack, midfield, defence, gk, value_£m, wage_£k/w, potential, is_wonderkid, pace, shooting, passing, dribbling, defending, physical)`
    : ` * ${helperName}(id, name, position, age, attack, midfield, defence, gk, value_£m, wage_£k/w, potential, is_wonderkid, pace, shooting, passing, dribbling, defending, physical)`;
  lines.push(sig);
  lines.push(' */');

  const params = hasNationality
    ? 'id,nm,nat,pos,age,atk,mid,def,gk,val,wage,pot,wk,pace,shooting,passing,dribbling,defending,physical'
    : 'id,nm,pos,age,atk,mid,def,gk,val,wage,pot,wk,pace,shooting,passing,dribbling,defending,physical';
  lines.push(`export const ${helperName} = (${params}) => ({`);
  const natField = hasNationality ? 'nationality:nat,' : '';
  lines.push(`  id,name:nm,${natField}position:pos,age,attack:atk,midfield:mid,defence:def,goalkeeping:gk,`);
  lines.push('  ...([pace,shooting,passing,dribbling,defending,physical].every(Number.isFinite) ? {attributeProfile:{version:1,pace,shooting,passing,dribbling,defending,physical}} : {}),');
  lines.push('  value:val*1_000_000,wage:wage*1_000,goals:0,assists:0,cleanSheets:0,form:50,');
  lines.push('  injured:false,suspended:false,inSquad:true,fitness:100,');
  lines.push('  ...(pot ? {potentialRating:pot} : {}),');
  lines.push('  ...(wk  ? {isWonderkid:true}    : {}),');
  lines.push('});\n');

  lines.push(`export const ${arrayName} = [`);
  for (const t of teams) {
    const players = [...(playersByTeam.get(t.team_id) || [])].sort(
      (a, b) => (POSITION_ORDER[a.position] ?? 99) - (POSITION_ORDER[b.position] ?? 99) || a.player_id.localeCompare(b.player_id)
    );
    const colorPart = t.primary_color ? `,primaryColor:'${t.primary_color}'` : '';
    lines.push(`  // ── ${t.name.toUpperCase()} ${'─'.repeat(Math.max(1, 55 - t.name.length))}`);
    lines.push(
      `  {id:'${t.team_id}',name:'${escapeJs(t.name)}',shortName:'${t.short_name}',crest:'${t.crest}',` +
      `league:'${escapeJs(t.league)}',stadium:'${escapeJs(t.stadium)}',stadiumCapacity:${t.stadium_capacity},` +
      `budget:${Math.round(Number(t.budget_millions) * 1_000_000)},reputation:${t.reputation}${colorPart},players:[`
    );
    for (const p of players) {
      const natArg = hasNationality ? `'${flagForDemonym(p.nationality)}',` : '';
      const detailed = DETAILED_ATTRIBUTE_KEYS.map(key => detailedArg(p, key)).join(',');
      lines.push(
        `    ${helperName}('${p.player_id}','${escapeJs(p.name)}',${natArg}'${p.position}',${p.age},` +
        `${p.attack},${p.midfield},${p.defence},${p.goalkeeping},${p.value_millions},${p.wage_thousands},` +
        `${p.potential || 0},${p.is_wonderkid ? 1 : 0},${detailed}),`
      );
    }
    lines.push('  ]},');
  }
  lines.push('];');
  return lines.join('\n') + '\n';
}
