<script>
  import { iconSvg } from '../../icons.mjs';

  let {
    name = 'info',
    size = 18,
    label = null,
    class: className = '',
  } = $props();

  // CSS masks let one semantic SVG registry inherit `currentColor` without
  // injecting raw markup into a Svelte component. The source is generated by
  // our own fixed registry, converted to solid black, then URI-encoded.
  const mask = $derived(
    `url("data:image/svg+xml,${encodeURIComponent(
      iconSvg(name, { size: 24 }).replaceAll('currentColor', '#000000'),
    )}")`,
  );
  const dimension = $derived(typeof size === 'number' ? `${size}px` : size);
</script>

<span
  class="icon {className}"
  style:width={dimension}
  style:height={dimension}
  style:--icon-mask={mask}
  role={label ? 'img' : null}
  aria-label={label}
  aria-hidden={label ? null : 'true'}
></span>

<style>
  .icon {
    display: inline-block;
    flex: 0 0 auto;
    vertical-align: middle;
    background: currentColor;
    -webkit-mask: var(--icon-mask) center / contain no-repeat;
    mask: var(--icon-mask) center / contain no-repeat;
  }
</style>
