#!/usr/bin/env python3
"""
csv_to_league.py — Convert CSV team/player data into a JS data file for PITCH.

Usage:
  python3 csv_to_league.py <teams_csv> <players_csv> <output_js> <array_name> <helper_fn>

Example:
  python3 csv_to_league.py \
    data/csv/championship_teams.csv \
    data/csv/championship_players.csv \
    data/championship.js \
    CHAMPIONSHIP_TEAMS \
    cp

The script:
  1. Reads teams CSV (team metadata) and players CSV (player stats)
  2. Joins players to teams by team_id
  3. Generates a JS file with the same format as plTeams.js / extraLeagues.js
  4. Validates: every team has players, every player has a valid team, ratings in range

CSV Schemas:
  teams.csv columns:
    team_id, name, short_name, crest, league, stadium, stadium_capacity,
    budget_millions, reputation, primary_color

  players.csv columns:
    team_id, player_id, name, nationality, position, age, attack, midfield, defence,
    goalkeeping, value_millions, wage_thousands[, potential, is_wonderkid]

  nationality: plain text country name e.g. "English", "Irish", "Jamaican"
  The converter maps this to a flag emoji and emits it as `nationality` on the player object.
"""

import csv, sys, os
from collections import defaultdict

# Map plain nationality text → flag emoji
NAT_FLAGS = {
    'English':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Scottish':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Welsh':'🏴󠁧󠁢󠁷󠁬󠁳󠁿','Northern Irish':'🇬🇧',
    'Irish':'🇮🇪','French':'🇫🇷','Spanish':'🇪🇸','German':'🇩🇪','Italian':'🇮🇹',
    'Portuguese':'🇵🇹','Dutch':'🇳🇱','Belgian':'🇧🇪','Brazilian':'🇧🇷','Argentine':'🇦🇷',
    'Colombian':'🇨🇴','Uruguayan':'🇺🇾','Chilean':'🇨🇱','Ecuadorian':'🇪🇨','Bolivian':'🇧🇴',
    'Peruvian':'🇵🇪','Venezuelan':'🇻🇪','Paraguayan':'🇵🇾','Mexican':'🇲🇽','American':'🇺🇸',
    'Canadian':'🇨🇦','Jamaican':'🇯🇲','Trinidadian':'🇹🇹','Barbadian':'🇧🇧',
    'Ghanaian':'🇬🇭','Nigerian':'🇳🇬','Senegalese':'🇸🇳','Ivorian':'🇨🇮','Cameroonian':'🇨🇲',
    'Congolese':'🇨🇩','Malian':'🇲🇱','Guinean':'🇬🇳','Sierra Leonean':'🇸🇱',
    'Gambian':'🇬🇲','Zimbabwean':'🇿🇼','South African':'🇿🇦','Angolan':'🇦🇴',
    'Mozambican':'🇲🇿','Ugandan':'🇺🇬','Kenyan':'🇰🇪','Tanzanian':'🇹🇿','Ethiopian':'🇪🇹',
    'Egyptian':'🇪🇬','Moroccan':'🇲🇦','Tunisian':'🇹🇳','Algerian':'🇩🇿','Libyan':'🇱🇾',
    'Polish':'🇵🇱','Czech':'🇨🇿','Slovak':'🇸🇰','Hungarian':'🇭🇺','Romanian':'🇷🇴',
    'Bulgarian':'🇧🇬','Croatian':'🇭🇷','Serbian':'🇷🇸','Bosnian':'🇧🇦','Slovenian':'🇸🇮',
    'Swedish':'🇸🇪','Norwegian':'🇳🇴','Danish':'🇩🇰','Finnish':'🇫🇮','Icelandic':'🇮🇸',
    'Swiss':'🇨🇭','Austrian':'🇦🇹','Greek':'🇬🇷','Turkish':'🇹🇷','Russian':'🇷🇺',
    'Ukrainian':'🇺🇦','Albanian':'🇦🇱','Macedonian':'🇲🇰','Montenegrin':'🇲🇪',
    'Japanese':'🇯🇵','South Korean':'🇰🇷','Chinese':'🇨🇳','Australian':'🇦🇺',
    'New Zealander':'🇳🇿','Indonesian':'🇮🇩','Thai':'🇹🇭',
    'Cape Verdean':'🇨🇻','Luxembourger':'🇱🇺','Belarusian':'🇧🇾',
    'Kosovan':'🇽🇰','Georgian':'🇬🇪','Armenian':'🇦🇲','Azerbaijani':'🇦🇿',
    'Liberian':'🇱🇷','Sierra Leonean':'🇸🇱','Burkinabe':'🇧🇫','Togolese':'🇹🇬',
    'Dominican':'🇩🇴','Haitian':'🇭🇹','Cuban':'🇨🇺','Puerto Rican':'🇵🇷',
}

def read_csv(path):
    with open(path, 'r', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def validate(teams, players):
    errors = []
    team_ids = {t['team_id'] for t in teams}
    player_teams = defaultdict(list)

    for p in players:
        player_teams[p['team_id']].append(p)
        # Validate ratings in range
        for stat in ['attack', 'midfield', 'defence', 'goalkeeping']:
            v = int(p[stat])
            if v < 1 or v > 99:
                errors.append(f"  {p['player_id']}: {stat}={v} out of range [1,99]")
        # Validate position
        valid_pos = {'GK','RB','LB','CB','CDM','CM','CAM','LM','RM','RW','LW','CF','ST'}
        if p['position'] not in valid_pos:
            errors.append(f"  {p['player_id']}: invalid position '{p['position']}'")
        # Validate age
        age = int(p['age'])
        if age < 15 or age > 45:
            errors.append(f"  {p['player_id']}: age={age} out of range [15,45]")

    for p in players:
        if p['team_id'] not in team_ids:
            errors.append(f"  Player {p['player_id']} references unknown team '{p['team_id']}'")

    for t in teams:
        count = len(player_teams.get(t['team_id'], []))
        if count < 11:
            errors.append(f"  Team {t['team_id']} ({t['name']}) has only {count} players (min 11)")
        if count > 30:
            errors.append(f"  Team {t['team_id']} ({t['name']}) has {count} players (max 30)")
        # Check at least 1 GK
        gks = [p for p in player_teams.get(t['team_id'], []) if p['position'] == 'GK']
        if len(gks) < 1:
            errors.append(f"  Team {t['team_id']} has no goalkeeper!")

    return errors, player_teams

def escape_js(s):
    return s.replace("'", "\\'")

def generate_js(teams, player_teams, array_name, helper_fn):
    lines = []
    lines.append(f"""/**
 * Auto-generated by csv_to_league.py
 * {len(teams)} teams, {sum(len(v) for v in player_teams.values())} players
 * League: {teams[0]['league'] if teams else 'Unknown'}
 *
 * {helper_fn}(id, name, nationality, position, age, attack, midfield, defence, gk, value_£m, wage_£k/w, potential, is_wonderkid)
 */""")

    # Helper accepts optional potential and is_wonderkid — baked in at data level
    # so assignPotentials() respects them rather than rolling random headroom.
    lines.append(f"const {helper_fn} = (id,nm,nat,pos,age,atk,mid,def,gk,val,wage,pot,wk) => ({{")
    lines.append(f"  id,name:nm,nationality:nat,position:pos,age,attack:atk,midfield:mid,defence:def,goalkeeping:gk,")
    lines.append(f"  value:val*1_000_000,wage:wage*1_000,goals:0,assists:0,cleanSheets:0,form:50,")
    lines.append(f"  injured:false,suspended:false,inSquad:true,fitness:100,")
    lines.append(f"  ...(pot ? {{potentialRating:pot}} : {{}}),")
    lines.append(f"  ...(wk  ? {{isWonderkid:true}}    : {{}}),")
    lines.append(f"}});\n")
    lines.append(f"const {array_name} = [")

    league_groups = defaultdict(list)
    for t in teams:
        league_groups[t['league']].append(t)

    for league, league_teams in league_groups.items():
        for t in league_teams:
            tid = t['team_id']
            players = player_teams.get(tid, [])
            # Sort: GK first, then by position
            pos_order = {'GK':0,'RB':1,'CB':2,'LB':3,'CDM':4,'CM':5,'CAM':6,'RM':7,'LM':8,'RW':9,'LW':10,'CF':11,'ST':12}
            players.sort(key=lambda p: (pos_order.get(p['position'], 99), p['player_id']))

            color_part = f",primaryColor:'{t['primary_color']}'" if t.get('primary_color') else ''
            lines.append(f"  // ── {t['name'].upper()} {'─'*(55 - len(t['name']))}")
            lines.append(f"  {{id:'{tid}',name:'{escape_js(t['name'])}',shortName:'{t['short_name']}',crest:'{t['crest']}',"
                         f"league:'{escape_js(t['league'])}',stadium:'{escape_js(t['stadium'])}',stadiumCapacity:{t['stadium_capacity']},"
                         f"budget:{int(float(t['budget_millions'])*1_000_000)},reputation:{t['reputation']}{color_part},players:[")

            for p in players:
                pid = p['player_id']
                nm = escape_js(p['name'])
                raw_nat = p.get('nationality', '').strip()
                nat_flag = NAT_FLAGS.get(raw_nat, '🌍')
                pos = p['position']
                age = int(p['age'])
                atk = int(p['attack'])
                mid = int(p['midfield'])
                dfn = int(p['defence'])
                gk = int(p['goalkeeping'])
                val = int(p['value_millions'])
                wage = int(p['wage_thousands'])
                pot = p.get('potential', '').strip()
                wk  = p.get('is_wonderkid', '').strip().lower()
                pot_arg  = f",{pot}"  if pot  else ",0"
                wk_arg   = ",1"       if wk in ('1','true','yes') else ",0"
                lines.append(f"    {helper_fn}('{pid}','{nm}','{nat_flag}','{pos}',{age},{atk},{mid},{dfn},{gk},{val},{wage}{pot_arg}{wk_arg}),")

            lines.append(f"  ]}},")

    lines.append(f"];")
    return '\n'.join(lines)


def main():
    if len(sys.argv) < 6:
        print(f"Usage: {sys.argv[0]} <teams_csv> <players_csv> <output_js> <array_name> <helper_fn>")
        print(f"Example: {sys.argv[0]} data/csv/championship_teams.csv data/csv/championship_players.csv data/championship.js CHAMPIONSHIP_TEAMS cp")
        sys.exit(1)

    teams_csv, players_csv, output_js, array_name, helper_fn = sys.argv[1:6]

    teams = read_csv(teams_csv)
    players = read_csv(players_csv)

    print(f"📊 Loaded {len(teams)} teams, {len(players)} players")

    errors, player_teams = validate(teams, players)
    if errors:
        print(f"❌ Validation errors:")
        for e in errors:
            print(e)
        sys.exit(1)

    print(f"✅ Validation passed")

    js = generate_js(teams, player_teams, array_name, helper_fn)

    # Resolve output path relative to script location or absolute
    if not os.path.isabs(output_js):
        base = os.path.dirname(os.path.abspath(__file__))
        output_js = os.path.join(base, output_js)

    with open(output_js, 'w', encoding='utf-8') as f:
        f.write(js + '\n')

    print(f"✅ Generated {output_js}")
    print(f"   {len(teams)} teams, {sum(len(v) for v in player_teams.values())} players")
    print(f"   Array: {array_name}, Helper: {helper_fn}()")

    # Print summary per team
    for t in teams:
        count = len(player_teams.get(t['team_id'], []))
        gks = len([p for p in player_teams.get(t['team_id'], []) if p['position'] == 'GK'])
        print(f"   {t['short_name']:4s} {t['name']:25s} {count:2d} players ({gks} GK)")


if __name__ == '__main__':
    main()
